### ISSUE TITLE
Fatal error: Class 'GoogleSafeBrowsing' 

### ISSUE THREAD

**Issue by novaidea** [dominykasgel/googlesafebrowsing#1]
Hello,
My code looks like this:

use \GoogleSafeBrowsing\GoogleSafeBrowsingServiceProvider;
GoogleSafeBrowsing::lookup( 'https://www.github.com' );

Fatal error: Class 'GoogleSafeBrowsing' not found in ...

laravel/framework is installed

what I am doing wrong?
Thanks

**Comment by dominykasgel** [comment]
Hi there,

Did you add a new service provider and alias to your config/app.php?

Add your new provider to the providers array of config/app.php:
`'providers' => [
    dominykasgel\GoogleSafeBrowsing\GoogleSafeBrowsingServiceProvider::class,
]`

Finally, add aliases to the aliases array of config/app.php: 
`'aliases' => [ 'GoogleSafeBrowsing' => dominykasgel\GoogleSafeBrowsing\Facades\GoogleSafeBrowsingFacade::class ]`

Also, not sure why you are using `use \GoogleSafeBrowsing\GoogleSafeBrowsingServiceProvider`

Let me know how it goes.

**Comment by novaidea** [comment]
Hello,

Yes. 

    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
		 
	dominykasgel\GoogleSafeBrowsing\GoogleSafeBrowsingServiceProvider::class, 
        Illuminate\Auth\AuthServiceProvider::class,
...
...
]

and

    'aliases' => [
		'GoogleSafeBrowsing' => dominykasgel\GoogleSafeBrowsing\Facades\GoogleSafeBrowsingFacade::class,
        'App' => Illuminate\Support\Facades\App::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
...
...
]

and still not working:
GoogleSafeBrowsing::lookup( 'https://www.github.com' ); - Fatal error: Class 'GoogleSafeBrowsing'

**Comment by dominykasgel** [comment]
Try to run `composer dump-autoload`

I justed tested the package on a fresh version of Laravel 5.2.45. What Laravel version you are using?
